#spring:
#  application:
#    name: spring-data-demo-1
#  datasource:
#    password: robeilaregawi
#    url: jdbc:postgresql://localhost:5433/lab9_db
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#server:
#  port: 8080
#  error:
#    include-message: always